### PR TITLE
update to jokes by andy

### PR DESCRIPTION
**Pull request by andydaiki**
i added some jokes I found on r/jokes cuz am lazy
also how do i italicize stuff in this language? (javascript??)

### CODE REVIEW

**Comment by za419** [comment]
CadenceBot uses Javascript for code and JSON for the config file. Italicizing can be done in the scripts by using Markdown - either asterisks or underscores should italicize text (The only italics in CadenceBot are done with underscores, italicizing one space...)

**Comment by za419** [comment]
I will wait to merge until you italicize, if you'd like.

**Comment by andydaiki** [comment]
how do i go back in and edit on this current pull request

**Comment by andydaiki** [comment]
nvm i found it

**Review by za419 — APPROVED** [review]
The spaces before newlines don't really do anything - they just appear as a space at the end of a line, which is invisible.

This does not negatively affect anything, so I will accept this.

**Pull request merged**
